apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns1
  name: ahmed-app
  labels:
    app: ahmed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ahmed-app
  template:
    metadata:
      labels:
        app: ahmed-app
    spec:
      containers:
        - name: ahmed-app
          image: ahmedmusa/express-crud-mongo:2.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_server
            - name: MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-db-name

---
apiVersion: v1
kind: Service
metadata:
  namespace: ns1
  name: ahmed-app-service
spec:
  selector:
    app: ahmed-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 3000
      nodePort: 30300
